/* 生成带错误探针 + 像素取样的页面副本，用于无头浏览器运行时诊断 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
// 必须与 index.html 同目录输出，否则 js/xxx.js 的相对路径会 404
const out = root;

let h = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

const probe = [
  '<script>',
  'window.__err = [];',
  'window.addEventListener("error", function (e) {',
  '  window.__err.push((e.message || String(e.error)) + " @ " +',
  '    String(e.filename || "").split("/").pop() + ":" + e.lineno + ":" + e.colno);',
  '});',
  'var _ce = console.error;',
  'console.error = function () { window.__err.push("console.error: " + Array.prototype.join.call(arguments, " ")); _ce.apply(console, arguments); };',
  '</' + 'script>'
].join('\n');

const tail = [
  '<script>',
  'window.__raf = 0;',
  '(function tick() { window.__raf++; requestAnimationFrame(tick); })();',
  'function _pre(id, txt) {',
  '  var p = document.createElement("pre"); p.id = id; p.textContent = txt;',
  '  document.body.appendChild(p);',
  '}',
  'setTimeout(function () {',
  '  _pre("__probe", "PROBE:" + JSON.stringify(window.__err));',
  '  _pre("__table", "TABLEROWS:" + document.querySelectorAll("#tbody-profile tr").length);',
  '  var tab = document.querySelector(\'.tab[data-tab="solid"]\');',
  '  if (tab) tab.click();',
  '  setTimeout(function () {',
  '    try {',
  '    var cv = document.getElementById("sa-canvas");',
  '    var box = cv.parentNode;',
  '    _pre("__env", "ENV:" + JSON.stringify({',
  '      rafTicks: window.__raf,',
  '      canvasAttr: [cv.width, cv.height],',
  '      boxClient: [box.clientWidth, box.clientHeight],',
  '      vizW: (window.__viz ? window.__viz.W : null),',
  '      vizH: (window.__viz ? window.__viz.H : null)',
  '    }));',
  '    // 无头环境 rAF 被节流，直接同步调一次 draw() 做确定性验证',
  '    if (window.__viz) window.__viz.draw();',
  '    } catch (e) { _pre("__drawerr", "DRAWERR:" + e.name + ": " + e.message + " | " + String(e.stack).split("\\n")[1]); }',
  '    var ctx = cv.getContext("2d");',
  '    var d = ctx.getImageData(0, 0, cv.width, cv.height).data;',
  '    var nonEmpty = 0, colors = {}, i, k;',
  '    for (i = 0; i < d.length; i += 4) {',
  '      if (d[i + 3] > 10) {',
  '        nonEmpty++;',
  '        k = (d[i] >> 4) + "-" + (d[i + 1] >> 4) + "-" + (d[i + 2] >> 4);',
  '        colors[k] = (colors[k] || 0) + 1;',
  '      }',
  '    }',
  '    var top = Object.keys(colors).map(function (c) { return [c, colors[c]]; })',
  '      .sort(function (a, b) { return b[1] - a[1]; }).slice(0, 6);',
  '    _pre("__visual", "VISUAL:" + JSON.stringify({',
  '      w: cv.width, h: cv.height, nonEmpty: nonEmpty,',
  '      distinct: Object.keys(colors).length, top: top',
  '    }));',
  '    _canvasBoxReport("canvas-heat", "__heat");',
  '    _canvasBoxReport("canvas-curve", "__curve");',
  '    _canvasBoxReport("planar-canvas", "__planar");',
  '    _canvasBoxReport("patch-canvas", "__patch");',
  '    _derivReport("__deriv");',
  '    _interactionReport();',
  '  }, 1500);',
  '}, 600);',
  'function _derivReport(outId) {',
  '  var ids = ["dv-sin","dv-circ","dv-da","dv-dA","dv-dOm","dv-theta",',
  '             "dv-omega","dv-pct","dv-exact","dv-approx","dv-err",',
  '             "dq-sin","dq-a","dq-b","dq-dA","dq-dOm","dq-dOm2","dq-theta",',
  '             "dq-cos","dq-cos2","dq-omega","dq-pct","dq-exact","dq-err"];',
  '  var r = {};',
  '  ids.forEach(function (id) {',
  '    var e = document.getElementById(id);',
  '    r[id] = e ? e.textContent : "MISSING";',
  '  });',
  '  _pre(outId, "DERIV:" + JSON.stringify(r));',
  '}',
  'function _interactionReport() {',
  '  var r = {};',
  '  var gi = function (id) { return document.getElementById(id); };',
  '  // 1) 按半光强光斑填充',
  '  gi("btn-spot").click();',
  '  r.spotFill_radius = gi("radius").value;',
  '  // 2) 切矩形',
  '  var rectRadio = document.querySelector(\'input[name="shape"][value="rect"]\');',
  '  rectRadio.checked = true;',
  '  rectRadio.dispatchEvent(new Event("change", { bubbles: true }));',
  '  r.rectFieldHidden = gi("field-rect").classList.contains("hidden");',
  '  r.circleFieldHidden = gi("field-R").classList.contains("hidden");',
  '  r.rectRows = document.querySelectorAll("#tbody-profile tr").length;',
  '  // 3) 切回圆形',
  '  var cirRadio = document.querySelector(\'input[name="shape"][value="circle"]\');',
  '  cirRadio.checked = true;',
  '  cirRadio.dispatchEvent(new Event("change", { bubbles: true }));',
  '  // 4) 改高度应联动',
  '  gi("height").value = "6";',
  '  gi("height").dispatchEvent(new Event("input", { bubbles: true }));',
  '  r.emax_at_h6 = gi("st-emax-v").textContent;',
  '  r.r50_at_h6 = gi("sum-r50").textContent;',
  '  gi("btn-reset-calc").click();',
  '  r.afterReset_emax = gi("st-emax-v").textContent;',
  '  r.afterReset_h = gi("height").value;',
  '  // 5) 立体角开关',
  '  gi("tg-cone").click();',
  '  r.coneOff = !gi("tg-cone").classList.contains("on");',
  '  r.vizConeShow = window.__viz ? window.__viz.show.cone : null;',
  '  gi("tg-cone").click();',
  '  // 6) 同步光束角',
  '  gi("btn-sa-sync").click();',
  '  r.syncedTheta = gi("sa-theta").value;',
  '  r.syncedOmega = gi("sa-omega-v").textContent;',
  '  // 7) 直接输入中心光强，应触发矛盾提示',
  '  gi("imax").value = "26000";',
  '  gi("imax").dispatchEvent(new Event("input", { bubbles: true }));',
  '  r.warnShown = gi("calc-note").className.indexOf("warn") >= 0;',
  '  r.emaxWithGivenImax = gi("st-emax-v").textContent;',
  '  gi("imax").value = "";',
  '  gi("imax").dispatchEvent(new Event("input", { bubbles: true }));',
  '  _pre("__interact", "INTERACT:" + JSON.stringify(r));',
  '}',
  'function _canvasBoxReport(id, outId) {',
  '  var cv = document.getElementById(id);',
  '  var ctx = cv.getContext("2d");',
  '  var W = cv.width, H = cv.height;',
  '  var d = ctx.getImageData(0, 0, W, H).data;',
  '  // 排除底部色标条（位于 H-22 起），但保留完整圆形区域',
  '  var lim = H - 42;',
  '  var minX = 1e9, maxX = -1, minY = 1e9, maxY = -1, n = 0;',
  '  for (var y = 0; y < lim; y++) {',
  '    for (var x = 0; x < W; x++) {',
  '      var a = d[(y * W + x) * 4 + 3];',
  '      if (a > 20) { n++; if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y; }',
  '    }',
  '  }',
  '  _pre(outId, "BBOX(" + id + "):" + JSON.stringify({',
  '    canvas: [W, H], cssClient: [cv.clientWidth, cv.clientHeight],',
  '    pixels: n, bbox: [minX, minY, maxX, maxY],',
  '    bboxW: (maxX - minX + 1), bboxH: (maxY - minY + 1),',
  '    aspect: n ? ((maxX - minX + 1) / (maxY - minY + 1)).toFixed(3) : null',
  '  }));',
  '}',
  '</' + 'script>'
].join('\n');

h = h.replace('<link rel="stylesheet"', probe + '\n<link rel="stylesheet"');
h = h.replace('</body>', tail + '\n</body>');

fs.writeFileSync(path.join(out, '__probe.html'), h);
console.log('probe 写入:', path.join(out, '__probe.html'), h.length, 'bytes');
